### ISSUE TITLE
o_egg.apk install error

### ISSUE THREAD

**Issue by jp1017** [bunnyblue/AndroidOOcquarium#1]
:sob: 兔兔

**Comment by bunnyblue** [comment]
android version @jp1017

**Comment by jp1017** [comment]
7.1.1, 4.4.2都不行

**Comment by bunnyblue** [comment]
done

**Comment by bunnyblue** [comment]
https://github.com/bunnyblue/AndroidOOcquarium/commit/6db8f8f962cdc06405c4196a05774e46d8f3f61e
